kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    registry: 'http://10.0.1.10:5000'
    repo: '10.0.1.10:5000/emo/copypaste'
    tags:
      - latest
      - '1.1'