kind: pipeline
name: default

steps:
- name: Build
  image: plugins/docker
  settings:
    registry: '10.0.1.10:5000'
    insecure: true
    repo: '10.0.1.10:5000/emo/copypaste'
    tags:
      - latest

- name: Test Playbook 
  image: plugins/ansible:3
  settings:
    playbook: deploy.yaml
    inventory: inventory
    galaxy: requirements.yaml
  syntax_check: true

- name: Deploy 
  image: plugins/ansible:3
  settings:
    playbook: deploy.yaml
    inventory: inventory
    galaxy: requirements.yaml
    user: "ben"
    private_key:
      from_secret: drone_ssh_key
    ssh_extra_args: "-o StrictHostKeyChecking=no"


- name: Notify
  image: appleboy/drone-telegram
  when:
    status:
      - success
      - failure
  settings:
    token:
      from_secret: telegram_token
    to:
      from_secret: telegram_user
    message: '{{#success build.status}}
        Build #{{build.number}} of {{repo.owner}}/{{repo.name}} succeeded. Commit message: "{{commit.message}}".
      {{else}}
        Build #{{build.number}} of {{repo.owner}}/{{repo.name}} failed. Commit message: "{{commit.message}}".\n\nView details [here]({{build.link}}).
      {{/success}}'
    format: markdown
    